I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/SCRIPT/battle/battle.rpy", line 3, in script call
    python:
  File "game/SCRIPT/battle/battle.rpy", line 3, in script call
    python:
  File "game/SCRIPT/battle/battle.rpy", line 3, in script call
    python:
  File "game/SCRIPT/battle/battle.rpy", line 3, in script call
    python:
  File "game/SCRIPT/battle/battle.rpy", line 3, in script call
    python:
  File "game/SCRIPT/battle/battle.rpy", line 3, in script call
    python:
  File "game/SCRIPT/battle/battle.rpy", line 3, in script call
    python:
  File "game/SCRIPT/battle/battle.rpy", line 3, in script
    python:
  File "game/SCRIPT/battle/battle.rpy", line 43, in <module>
    renpy.call_screen("timer_screen")
  File "renpy/common/00action_other.rpy", line 537, in __call__
    rv = self.callable(*self.args, **self.kwargs)
  File "game/SCRIPT/functions.rpy", line 83, in swap_wrestler_up
    uno = team[0]
NameError: global name 'team' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/SCRIPT/battle/battle.rpy", line 3, in script call
    python:
  File "game/SCRIPT/battle/battle.rpy", line 3, in script call
    python:
  File "game/SCRIPT/battle/battle.rpy", line 3, in script call
    python:
  File "game/SCRIPT/battle/battle.rpy", line 3, in script call
    python:
  File "game/SCRIPT/battle/battle.rpy", line 3, in script call
    python:
  File "game/SCRIPT/battle/battle.rpy", line 3, in script call
    python:
  File "game/SCRIPT/battle/battle.rpy", line 3, in script call
    python:
  File "game/SCRIPT/battle/battle.rpy", line 3, in script
    python:
  File "renpy/ast.py", line 913, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2111, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/SCRIPT/battle/battle.rpy", line 43, in <module>
    renpy.call_screen("timer_screen")
  File "renpy/exports.py", line 2969, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "renpy/display/core.py", line 2978, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "renpy/display/core.py", line 3776, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "renpy/display/layout.py", line 1027, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "renpy/display/layout.py", line 1027, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "renpy/display/layout.py", line 1027, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "renpy/display/screen.py", line 720, in event
    rv = self.child.event(ev, x, y, st)
  File "renpy/display/layout.py", line 1027, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "renpy/display/behavior.py", line 466, in event
    rv = run(action)
  File "renpy/display/behavior.py", line 323, in run
    return action(*args, **kwargs)
  File "renpy/common/00action_other.rpy", line 537, in __call__
    rv = self.callable(*self.args, **self.kwargs)
  File "game/SCRIPT/functions.rpy", line 83, in swap_wrestler_up
    uno = team[0]
NameError: global name 'team' is not defined

